### ISSUE TITLE
'CIFAR10' object has no attribute 'train_labels'

### ISSUE THREAD

**Issue by vojtooo** [EricArazo/PseudoLabeling#3]
Hi,

I have cloned your repository to try out, but when I run `./RunScripts_SOTA500.sh` I get

```(Development) ./RunScripts_SOTA500.sh
INFO:root:Namespace(DA='jitter', DApseudolab='False', M=[], Mixup_Alpha=1, alpha=0.8, batch_size=100, beta=0.4, cuda_dev=0, dataset='cifar10', dataset_type='sym_noise_warmUp', download=True, drop_extra_forward='True', dropout=0.1, epoch=10, epoch_begin=0, epoch_update=1, experiment_name='WuP_model', gausTF=False, initial_epoch=0, label_noise=0.0, labeled_batch_size=16, labeled_samples=500, loss_term='MixUp_ep', lr=0.1, momentum=0.9, network='MT_Net', num_classes=10, out='./data/model_data', relab='unifRelab', save_checkpoint='False', seed=1, seed_val=1, swa='True', swa_freq=5, swa_lr=-0.01, swa_start=350, test_batch_size=100, train_root='./data', val_samples=5000, validation_exp='False', wd=0.0001)
Files already downloaded and verified
Traceback (most recent call last):
  File "train.py", line 461, in <module>
    main(args, dst_folder)
  File "train.py", line 198, in main
    train_loader, test_loader, train_noisy_indexes = data_config(args, transform_train, transform_test,  dst_folder)
  File "train.py", line 83, in data_config
    trainset, clean_labels, noisy_labels, train_noisy_indexes, train_clean_indexes, valset = get_dataset(args, transform_train, transform_test, dst_folder)
  File "/PseudoLabeling/cifar10/dataset/cifar10.py", line 12, in get_dataset
    train_indexes, val_indexes = train_val_split(args, cifar10_train_val.train_labels)
AttributeError: 'CIFAR10' object has no attribute 'train_labels'
INFO:root:Namespace(DA='jitter', DApseudolab='False', M=[250, 350], Mixup_Alpha=1, alpha=0.8, batch_size=100, beta=0.4, cuda_dev=0, dataset='cifar10', dataset_type='semiSup', download=True, drop_extra_forward='True', dropout=0.1, epoch=400, epoch_begin=0, epoch_update=1, experiment_name='M_SOTA_CIFAR10', gausTF=False, initial_epoch=10, label_noise=0.0, labeled_batch_size=16, labeled_samples=500, loss_term='MixUp_ep', lr=0.1, momentum=0.9, network='MT_Net', num_classes=10, out='./data/model_data', relab='unifRelab', save_checkpoint='False', seed=1, seed_val=1, swa='True', swa_freq=5, swa_lr=-0.01, swa_start=350, test_batch_size=100, train_root='./data', val_samples=5000, validation_exp='False', wd=0.0001)
Files already downloaded and verified
Traceback (most recent call last):
  File "train.py", line 461, in <module>
    main(args, dst_folder)
  File "train.py", line 198, in main
    train_loader, test_loader, train_noisy_indexes = data_config(args, transform_train, transform_test,  dst_folder)
  File "train.py", line 83, in data_config
    trainset, clean_labels, noisy_labels, train_noisy_indexes, train_clean_indexes, valset = get_dataset(args, transform_train, transform_test, dst_folder)
  File "/PseudoLabeling/cifar10/dataset/cifar10.py", line 12, in get_dataset
    train_indexes, val_indexes = train_val_split(args, cifar10_train_val.train_labels)
AttributeError: 'CIFAR10' object has no attribute 'train_labels'

```

Can you please help me out?
Thank you :)

**Comment by EricArazo** [comment]
Hello Vojtooo,

Thank you for your interest in our work. Your problem might be because of your torchvision/PyTorch version. In recent versions, the variable for the labels for the training samples in torchvision.datasets.CIFAR10 is not called "train_labels" anymore, instead, it is called "targets". Consequently, you have to change the "train_labels" variable for "targets" everywhere in the file /cifar10/dataset/cifar10.py.

That (or changing your version of torchvision/PyTorch) should make it work.

Feel free to ask any other questions.

Best,
Eric

**Comment by alexvbogdan** [comment]
Hi,

I have just noticed it also applies to `AttributeError 'CIFAR10' object has no attribute 'train_data'`.
It has the same source of problem as Eric mentioned and is similarly solved by changing 'train_data' to 'data'.
Hope it will be helpful for others.
